### ISSUE TITLE
Cannot compile on linux

### ISSUE THREAD

**Issue by wtrocki** [chirino/graphql#1]
Compilation for linux fails:

error=failed to build for linux_386: # github.com/chirino/graphql/internal/scanner
../../../../pkg/mod/github.com/chirino/graphql@v0.0.0-20200428200219-be238e24924c/internal/scanner/scanner.go:596:31: constant 4294977024 overflows int

go version go1.14.2 darwin/amd64

**Comment by chirino** [comment]
Ohh. Sounds like a bug we need to fix.

**Comment by wtrocki** [comment]
This is very specific to distribution builds. Running go build works for both graphql and graphql-gw

**Comment by chirino** [comment]
I can reproduce using: `GOOS=linux GOARCH=386 go test ./...`

**Comment by chirino** [comment]
fixed now
